# Generated by Django 4.1.4 on 2023-02-25 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseCode', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('courseName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('studentName', models.TextField()),
                ('password', models.TextField(default='NULL')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectCode', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('subjectName', models.TextField()),
                ('credithours', models.IntegerField()),
                ('lecturerName', models.TextField()),
                ('courseCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetable.course')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('assignName', models.TextField()),
                ('dateOut', models.DateField()),
                ('dateIn', models.DateField()),
                ('submit', models.TextField(default='UNSUBMITED')),
                ('courseCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetable.course')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetable.student')),
                ('subjectCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetable.subject')),
            ],
        ),
    ]
