# Generated by Django 4.1.7 on 2023-02-27 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0002_delete_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignName', models.TextField()),
                ('dateOut', models.DateField()),
                ('dateIn', models.DateField()),
                ('submit', models.TextField(default='UNSUBMITED')),
                ('subjectCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetable.subject')),
            ],
        ),
    ]
